#! /bin/bash

cd $(dirname $0)

# Vim setup
ln -s vim ~/.vim/
ln -s vimrc ~/.vimrc
ln -s tmux.conf ~/.tmux.conf
ln -s gitconfig ~/.gitconfig

cd ~/.vim
git submodule update --init
vim +PluginInstall +qall

cd ~

sudo apt-get install -y curl tree unzip zip

sudo wget -q0 /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein

